flags:
  time-locale-compat:
    old-locale: false
user-message: ! 'Warning (added by new or init): Specified resolver could not satisfy
  all dependencies. Some external packages have been added as dependencies.

  You can omit this message by removing it from stack.yaml

'
packages:
- .
extra-deps:
- HUnit-1.6.0.0
- QuickCheck-2.11.3
- StateVar-1.1.0.4
- adjunctions-4.4
- aeson-1.3.1.0
- aeson-pretty-0.8.7
- aeson-qq-0.8.2
- ansi-terminal-0.8.0.2
- ansi-wl-pprint-0.6.8.2
- appar-0.1.4
- async-2.2.1
- attoparsec-0.13.2.2
- attoparsec-iso8601-1.0.0.0
- auto-update-0.1.4
- base-compat-0.9.3
- base-orphans-0.7
- base64-bytestring-1.0.0.1
- basement-0.0.7
- bifunctors-5.5.2
- blaze-builder-0.4.1.0
- blaze-html-0.9.0.1
- blaze-markup-0.8.2.1
- bsb-http-chunked-0.0.0.2
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- cabal-doctest-1.0.6
- call-stack-0.1.0
- case-insensitive-1.2.0.11
- clock-0.7.2
- cmdargs-0.10.20
- colour-2.3.4
- comonad-5.0.3
- contravariant-1.4.1
- control-monad-omega-0.3.1
- cookie-0.4.4
- cpphs-1.20.8
- cryptonite-0.25
- data-default-class-0.1.2.0
- distributive-0.5.3
- dlist-0.8.0.4
- easy-file-0.2.1
- exceptions-0.10.0
- fail-4.9.0.0
- fast-logger-2.4.11
- file-embed-0.0.10.1
- foundation-0.0.20
- free-5.0.1
- hashable-1.2.7.0
- haskell-src-exts-1.20.2
- haskell-src-meta-0.8.0.2
- hspec-2.5.0
- hspec-core-2.5.0
- hspec-discover-2.5.0
- hspec-expectations-0.8.2
- hspec-wai-0.9.0
- hspec-wai-json-0.9.0
- http-api-data-0.3.8.1
- http-client-0.5.12
- http-date-0.0.6.1
- http-media-0.7.1.2
- http-types-0.12.1
- http2-1.6.3
- integer-logarithms-1.0.2.1
- iproute-1.7.3
- kan-extensions-5.1
- lens-4.16.1
- lifted-base-0.2.3.12
- memory-0.14.16
- mime-types-0.1.0.7
- mmorph-1.1.2
- monad-control-1.0.2.3
- mtl-2.2.2
- natural-transformation-0.4
- network-2.6.3.5
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.14.2.0
- parallel-3.2.1.1
- parsec-3.1.13.0
- polyparse-1.12
- primitive-0.6.3.0
- profunctors-5.2.2
- psqueues-0.2.6.0
- quickcheck-io-0.2.0
- random-1.1
- reflection-2.1.3
- resourcet-1.2.1
- safe-0.3.17
- scientific-0.3.5.3
- semigroupoids-5.2.2
- semigroups-0.18.4
- servant-0.13
- servant-docs-0.11.2
- servant-multipart-0.11
- servant-server-0.13
- setenv-0.1.1.3
- simple-sendfile-0.2.27
- singleton-bool-0.1.4
- split-0.2.3.3
- stm-2.4.5.0
- streaming-commons-0.2.0.0
- string-conversions-0.4.0.1
- stringsearch-0.3.6.6
- syb-0.7
- system-filepath-0.4.14
- tagged-0.8.5
- text-1.2.3.0
- tf-random-0.5
- th-abstraction-0.2.6.0
- th-expand-syns-0.4.4.0
- th-lift-0.7.8
- th-lift-instances-0.1.11
- th-orphans-0.13.5
- th-reify-many-0.1.8
- time-locale-compat-0.1.1.4
- transformers-base-0.4.5.2
- transformers-compat-0.6.1.5
- unix-compat-0.5.0.1
- unix-time-0.3.8
- unliftio-core-0.1.1.0
- unordered-containers-0.2.9.0
- uri-bytestring-0.3.1.1
- utf8-string-1.0.1.1
- uuid-types-1.0.3
- vault-0.3.1.0
- vector-0.12.0.1
- void-0.7.2
- wai-3.2.1.2
- wai-app-static-3.1.6.2
- wai-extra-3.0.22.1
- wai-logger-2.3.2
- warp-3.2.18.2
- word8-0.1.3
- zlib-0.6.2
resolver: ghc-8.0.2
